{{- if .Values.dockerPullSecrets.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  {{- if .Values.image.pullSecrets }}
  {{- range  $value := .Values.image.pullSecrets }}
  name: {{ $value }}
  {{- end }}
  {{- else }}
  {{- range  $value := .Values.global.imagePullSecrets }}
  name: {{ $value }}
  {{- end }}
  {{- end }}
data:
  .dockerconfigjson: {{ .Values.dockerPullSecrets.dockerconfigjson }}
{{- end }}
